### ISSUE TITLE
cpuset cgroup needed in pi/zero release pls ;)

### ISSUE THREAD

**Issue by sokoow** [Re4son/re4son-kernel-builder#12]
Hiya,

I'm playing with k3s on your kernel with various pis: https://github.com/rancher/k3s/issues/64

Can cpuset be enabled in this kernel pls ?

```
WARN[2019-03-03T14:44:25.432884090Z] Failed to find cpuset cgroup, you may need to add "cgroup_enable=cpuset" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi) 
```
afaik k3s and k8s in general needs memory and cpuset namespaces at least. Memory seems to be there already.

**Comment by steev** [comment]
`CONFIG_CPUSETS=y` is already set in the kernel.  Can you try adding the `cgroup_enable=cpuset` to the /boot/cmdline.txt file as it recommends and see if it works?

**Comment by steev** [comment]
Disregard, I misread, that change would be required in the rpi1 config, you are correct, it doesn't appear to be set.

**Comment by sokoow** [comment]
I didn't look it up, but is there any way to set two namespaces on when using kernel args ? Seems like k3s/kubeadm need both cpuset and memset, do I just do cgroup_enable=cpuset,memset ?

**Comment by steev** [comment]
Looking into it, it doesn't seem possible to do it for the pi/zero.  The kernel config for CPUSETS relies on SMP, which isn't possible to turn on for the pi1/zero

**Comment by sokoow** [comment]
Good to know, also not a big bother, kube will just run without these limits I guess. Thanks for helping digging it.

**Comment by steev** [comment]
Basically, cpusets is used to set which processors are used, so you can constrain it to say, cpus 1 and 3 - but the pi/zero is single core, so you can’t really say to use other cores.
