### ISSUE TITLE
Recent Build of the Kali-Pi Kernel Missing /boot/overlays/dwc2.dtbo

### ISSUE THREAD

**Issue by necopinus** [Re4son/re4son-kernel-builder#14]
I'm not 100% sure if this is the right repo to file this bug in. Happy to refile.

This bug was [originally filed](https://bugs.kali.org/view.php?id=7469) for the Kali Linux `kalipi-kernel` package version 5.4.83-20211127. That recent build of the re4son kernel is missing `/boot/overlays/dwc2.dtbo`; this breaks USB gadget mode (necessary, for example, to [connect the RPi to a device like an iPad using USB C using only a single cable](https://gist.github.com/necopinus/9a961f001f031477216b1b68b336fe20) or to [set up ethernet gadgets in general](https://re4son-kernel.com/re4son-pi-kernel/)). This file was present in version 5.4.83-20210516 of the Kali Linux package.

It was [suggested in the original report that I file this bug with you](https://bugs.kali.org/view.php?id=7469#c15479) in case the exclusion of this file is purposeful.

**Comment by Re4son** [comment]
Thanks for letting me know. I much appreciate it.
I've fixed it here:
https://github.com/Re4son/kalipi-firmware/compare/20211127kali...20211204kali
You will get the updated packages with your next "apt upgrade"
