### ISSUE TITLE
usb over-current change kmesg flooding

### ISSUE THREAD

**Issue by akhepcat** [Re4son/re4son-kernel-builder#6]
Linux kali-pi 4.14.50-Re4son-v7+ #4 SMP Thu Jul 19 11:07:19 AEST 2018 armv7l GNU/Linux

Using the official PoE hat on the 3B+ with the above kernel results in continuous logging of usb over-current change messages:
$ dmesg | tail
[ 2210.071687] usb 1-1-port2: over-current change
[ 2210.081690] usb 1-1.1-port3: over-current change
[ 2210.311689] usb 1-1-port3: over-current change
[ 2210.321691] usb 1-1.1-port2: over-current change
[ 2210.551684] usb 1-1-port4: over-current change
[ 2210.562041] usb 1-1.1-port3: over-current change
[ 2210.791710] usb 1-1-port2: over-current change
[ 2210.802037] usb 1-1.1-port2: over-current change
[ 2211.031708] usb 1-1-port3: over-current change
[ 2211.042063] usb 1-1.1-port3: over-current change
[ 2211.271714] usb 1-1-port4: over-current change
[ 2211.282140] usb 1-1.1-port2: over-current change
[ 2211.511725] usb 1-1-port2: over-current change
[ 2211.522092] usb 1-1.1-port3: over-current change
[ 2211.751751] usb 1-1-port3: over-current change

Nothing is plugged into any USB ports at this time (only the onboard ethernet)
$ lsusb -t
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=dwc_otg/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M
        |__ Port 1: Dev 3, If 0, Class=Hub, Driver=hub/3p, 480M
            |__ Port 1: Dev 5, If 0, Class=Vendor Specific Class, Driver=lan78xx, 480M

Hadn't booted in a while, so just upgraded today
$ uptime
 20:08:06 up 41 min,  1 user,  load average: 2.22, 2.12, 2.02
$ grep Sep kern.log | wc -l
82143

2000 messages per minute is pretty noisy, especially given that there doesn't seem to be any reason for this.

**Comment by Re4son** [comment]
Thanks for letting me know.
I can see some raspberry pi firmware commits that contain some poe dtbo stuff. I'll pull them and compile a new kernel. I'm away for the week but will get to it next weekend.

**Comment by akhepcat** [comment]
Looks like this might be a hardware issue with the official PoE hat itself, so i think I'll close this as a no-op.
